version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
  

